export const API_BASE_URL = 'http://localhost:8080/api/v1'
export const SIGN_UP_URL = 'auth/register'
export const SIGN_IN_URL = 'auth/authenticate'
export const REFRESH_TOKEN_URL = 'auth/refresh-token'
export const TIMELINE_URL = 'timelines'
export const TIMELINE_BULK_URL = 'timelines/bulk'
export const TIMELINE_EVENTS_URL = 'timelines/events'
export const TIME_EVENT_URL = 'timeEvents'
